### ISSUE TITLE
two submissions on the one model?

### ISSUE THREAD

**Issue by mwotton** [tcocca/dynamic_forms#2]
I'm trying to attach two form submissions to the one model. (In this case, it's a Rule which has both a trigger and an action, each of which is represented as a form submission.)

Is there any way of handling this inside one class, or should i just split it off to TriggerInstance with a has_one relationship to form_submission, and a belongs_to relationship to Rule?

**Comment by mwotton** [comment]
nevermind, i'm an idiot. much easier to have two belongs_to relationships on Rule.

**Comment by tcocca** [comment]
Right, I was going to say, you could have something like:

belongs_to :trigger, :class => FormSubmission, :foreign_key => :trigger_id
belongs_to :action, :class => FormSubmission, :foreign_key => :action_id

Not sure if this is what you decided to go with or not (may need to check the syntax as well) but that should be something like what you are looking for.

~ Tom

**Comment by mwotton** [comment]
yep, worked like a charm.
